apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: wehaul-fleet-management-api
  description:  The awesome WeHaul API
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  system: wehaul-fleet-management-app
  definition:
    $text: https://github.com/santiagovm/tap-hackathon-fleet-management/blob/main/catalog/api-docs.json