apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wehaul-fleet-management-app
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=wehaul-fleet-management-app"
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  providesApis:
    - wehaul-fleet-management-api
  consumesApis:
    - rental-manager-dotnet-api
  dependsOn:
    - service:team-b/rental-manager
