CREATE TABLE TRUCK (
    TRUCK_ID                SERIAL PRIMARY KEY,
    MILES                   INTEGER NOT NULL,
    LAST_INSPECTION_MILES   INTEGER NOT NULL,
    AVAILABLE               BOOLEAN NOT NULL,
    AVAILABILITY_REASON     VARCHAR(255) NULL
);
